#ifndef CURRENT_EXPRESSION_MATH_FUNCTION
#error "Must `#define` `CURRENT_EXPRESSION_MATH_FUNCTION` before `#include`-ing `math_functions.inl`."
#endif

CURRENT_EXPRESSION_MATH_FUNCTION(exp)
CURRENT_EXPRESSION_MATH_FUNCTION(log)
CURRENT_EXPRESSION_MATH_FUNCTION(sin)
CURRENT_EXPRESSION_MATH_FUNCTION(cos)
CURRENT_EXPRESSION_MATH_FUNCTION(tan)
