#ifndef CURRENT_EXPRESSION_MATH_OPERATION
#error "Must `#define` `CURRENT_EXPRESSION_MATH_OPERATION` before `#include`-ing `math_operations.inl`."
#endif

CURRENT_EXPRESSION_MATH_OPERATION(+, Plus, add)
CURRENT_EXPRESSION_MATH_OPERATION(-, Minus, sub)
CURRENT_EXPRESSION_MATH_OPERATION(*, Multiply, mul)
CURRENT_EXPRESSION_MATH_OPERATION(/, Divide, div)
