#ifndef CURRENT_EXPRESSION_MATH_OPERATION
#error "Must `#define` `CURRENT_EXPRESSION_MATH_OPERATION` before `#include`-ing `math_operations.inl`."
#endif

CURRENT_EXPRESSION_MATH_OPERATION(+, add)
CURRENT_EXPRESSION_MATH_OPERATION(-, sub)
CURRENT_EXPRESSION_MATH_OPERATION(*, mul)
CURRENT_EXPRESSION_MATH_OPERATION(/, div)
